### Numpy

Numpy is a fundamental library for scientific computing in Python.It provides support for arrays and matrices,along with a collection of mathematical functions to operate on these data structures.

In [2]:
!pip install numpy

In [3]:
import numpy as np
# create array using numpy
# create a 1D array
arr1=np.array([1,2,3,4,5]) # np.array() is a function to create an array
print(arr1)
print(type(arr1))# it is not a list its a n dimension array
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
# 1D array
arr2=np.array([1,2,3,4,5])
arr2.reshape((1,5)) # here 1,5 means 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2.reshape((5,1))

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [6]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
# 2D array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape) # output is 2,5 bcz 2 rows and 5 columns

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [9]:
np.arange(0,10,2).reshape(5,1) # here 1,10 is range and 2 is step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4))# this function creates a array with 3 rows and 4 columnsand all are 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of numpy array
arr=np.array([[1,2,3],[4,5,6]])

print("Array :\n",arr)
print("Shape :",arr.shape)
print("Number of dimensions",arr.ndim)
print("Size(number of elements)",arr.size)
print("Data type:",arr.dtype)
print("Item size(in bytes)",arr.itemsize)

Array :
 [[1 2 3]
 [4 5 6]]
Shape : (2, 3)
Number of dimensions 2
Size(number of elements) 6
Data type: int64
Item size(in bytes) 8


In [12]:
## Numpy Vectorized operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

# Element Wise addition
print("Addition : ",arr1+arr2)
# Element Wise Substraction
print("Substraction : ",arr1-arr2)
# Element Wise Multiplication
print("Substraction : ",arr1*arr2)
# Element Wise Division
print("Substraction : ",arr1/arr2)

Addition :  [11 22 33 44 55]
Substraction :  [ -9 -18 -27 -36 -45]
Substraction :  [ 10  40  90 160 250]
Substraction :  [0.1 0.1 0.1 0.1 0.1]


In [14]:
## Universal Function
arr=np.array([2,3,4,5,6])
# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# Natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [23]:
## Array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array :\n",arr)

Array :
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
int(arr[0][0])

1

In [34]:
arr[0:2,2:]

array([[3, 4],
       [7, 8]])

In [27]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [29]:
arr[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12]])

In [36]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [37]:
# Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [38]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [39]:
# Statistical concepts-Normalization
# To have a mean of 0 and standard deviation of 1
data=np.array([1,2,3,4,5])

# calculate mean and standard deviation
mean=np.mean(data)
std_div=np.std(data)

# Normalize the data
normalized_data=(data - mean)/std_div
print("Normalized data : ",normalized_data)

Normalized data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [42]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean=np.mean(data)
print("Mean :",mean)

# Median
median=np.median(data)
print("Median :",median)

# Standard deviation
std_div=np.std(data)
print("Standard Deviation :",std_div)

# Variance
variance=np.var(data)
print("Variance :",variance)



Mean : 5.5
Median : 5.5
Standard Deviation : 2.8722813232690143
Variance : 8.25


In [50]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >= 5)& (data <=8)]

array([5, 6, 7, 8])